### ISSUE TITLE
copyrights?  Licenses?

### ISSUE THREAD

**Issue by jeffcrilly** [rackerlabs/repose#1253]
I see there are no copyrights or license text in the repose source files (fwiw, I only checked some.)

Likewise there is no license information in rackspace maven.  E.g.
https://maven.research.rackspacecloud.com/content/groups/aggregate/com/rackspace/papi/components/datastore-distributed/6.2.2.0/datastore-distributed-6.2.2.0.pom  does not have any license information.

While i do see the license info at the top of this github account, the expectation is license would also be in packaged deliverables.

(E.g. compare with https://repo1.maven.org/maven2/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.pom which has a present <licenses> element.)

This is not critical, but for consumers that need to track license usage, having the license info present helps with any license compliance processes that consumer might be implementing.

**Comment by karidavis** [comment]
Hi Jeff - thanks for your question.  We have our licensing information here:
https://repose.atlassian.net/wiki/display/REPOSE/License

The team is taking a break today after a grueling week.  Please respond back if this doesn't help you.  Thanks - Kari
