### ISSUE TITLE
Next release date

### ISSUE THREAD

**Issue by ganeshs** [rackerlabs/repose#1322]
I'm dependent on a couple of resolved issues in the trunk. Any timelines on when the next release will be out?

Thanks,
Ganesh

**Comment by adrianjgeorge** [comment]
We released last week, has something made it into master since then that you need?

**Comment by adrianjgeorge** [comment]
It was 7.1.2.0

**Comment by ganeshs** [comment]
Thanks. I have my fixes included in that version.

-Ganesh
