### ISSUE TITLE
maxElementsInMemory for Ehcache in datastore manager in hardcoded, which should be configurable

### ISSUE THREAD

**Issue by vishal-kedia** [rackerlabs/repose#1327]
maxElementsInMemory = 20000 for Ehcache in EHCacheDatastoreManager is hardcoded, which should be configurable.

**Comment by dmnjohns** [comment]
Fair enough. I'll make sure the team takes a look at this request. Thanks for pointing it out!

**Comment by karidavis** [comment]
Hi Vishal - i'd like to learn a little more about your use case with Repose.  Are you external to Rackspace?  If yes, can you tell me who you are with and what your use case is?

**Comment by srini156** [comment]
@karidavis, We are using repose external to rackspace & will send out details (use case, our custom extensions etc.) via email to  - reposecore@rackspace.com.

**Comment by wdschei** [comment]
This is being tracked on our backlog here: https://repose.atlassian.net/browse/REP-3024
and the groundwork testing was started here: https://github.com/rackerlabs/repose/compare/REP-3007
