### ISSUE TITLE
is there any way to switch off the VIA header in repose response.

### ISSUE THREAD

**Issue by vishal-kedia** [rackerlabs/repose#1328]

**Comment by dmnjohns** [comment]
Hi Vishal,

In the future, could you please posts questions like this to the Repose Questions board? You can get there by navigating to: https://repose.atlassian.net/wiki/questions

Alternatively, if the content of your question is private, send an email to reposecore@rackspace.com.

Anyway, to answer your question, there is not currently a way to switch off the VIA header in Repose responses. You can, however, change the value of that header by modifying your container.cfg.xml file. See: https://repose.atlassian.net/wiki/display/REPOSE/Container#Container-ElementsandAttributes

Thanks,
Damien

**Comment by vishal-kedia** [comment]
thanks Damien
