### ISSUE TITLE
HTTP health check URL for repose

### ISSUE THREAD

**Issue by toddlers** [rackerlabs/repose#1351]
We have a use case with AWS. Repose service is exposed via an ELB. As of now the health checks are based on TCP,but that's causing issues , as service is up but its giving HTTP 5xx because some filters did not got loaded and it throws some exception in the logs says repose is not ready.

How about we have a HTTP health check URL for checking repose healthiness. So consider when we are loading the filters chain and something goes wrong in between , we log repose is not ready in the log file and  that HTTP health check would return some HTTP code apart from 200 for that health check URL in that way ELB will get to know if repose is not ready.

In this way it will take the repose service box out of rotation.

Ultimate goal is to know the status of the cluster via a HTTP call.

**Comment by wdschei** [comment]
This has been on our backlog for a while and is being tracked here: https://repose.atlassian.net/browse/REP-1328
