### ISSUE TITLE
repose-valve startup script no longer honors $JAVA

### ISSUE THREAD

**Issue by jguice** [rackerlabs/repose#1396]
The java version check introduced by 4eac73b82ef037decb1fa707f3a7171e7b91db68 isn't using the `/etc/sysconfig/repose` `$JAVA` environment variable.  We don't use the java on the path (and the path java is < 1.7) so repose isn't starting at the moment.

I started to make a PR for this, but wasn't sure if all the new "java executable on the path" statements needed updating as well.  Does it really require a java executable on the path, or just a valid (and > 1.7) java executable referenced by `$JAVA`? :smile:

**Comment by dmnjohns** [comment]
As far as I can tell, the script does not actually necessitate that a Java executable be on the path. Setting it in /etc/sysconfig/repose should do just fine. In which case, I'd love to see a PR for this!

Side note: can you remind me which project you're working on?

**Comment by dmnjohns** [comment]
I went ahead and made the changes (#1404) . Closing this issue. =)

**Comment by jguice** [comment]
Thanks, sorry just hadn't gotten back to this yet.  Working on actually deploying repose to production for monitoring (#maas). ;)

I was thinking the comments and messaging should be updated to reflect that it's not actually the PATH java that matters but what's defined in /etc/sysconfig.

e.g.

```bash
echo "/etc/sysconfig/repose JAVA=$JAVA doesn't point to a valid java"
```

And a similar output when it's valid but not a high enough version.

Could maybe even try the path java too and emit a warning about /etc/sysconfig/repose JAVA being invalid but a valid path java being found and used instead if you want to get fancy. ;)

This should fix the problem though. :)

**Comment by dmnjohns** [comment]
No problem.

Yeah, I totally skipped updating the comments. I chalk it up to doing this is in the morning. I'll fix that.

I considered using the path Java as a fallback, but then got lazy. I guess I'll go ahead and add that as well.

**Comment by jguice** [comment]
Awesome!  I'd be happy to test it out.
