### ISSUE TITLE
[LOGJAM] Allow for the ability to increase the DH key size

### ISSUE THREAD

**Issue by gtmanfred** [rackerlabs/repose#1406]
To mitigate the logjam vulnerability in ssl, we need to be able to increase the DHParam key size from the default, which is 512 bits, to 2048 bits, like you can with nginx or apache by providing a larger key to use, or just setting to use a larger value.

https://cipherli.st/

It looks like java 7 does not work for this in certain situations.

https://wiki.mozilla.org/Security/Server_Side_TLS#DHE_and_Java
https://wiki.mozilla.org/Security/Server_Side_TLS#Logjam_attack_on_weak_Diffie-Hellman

https://weakdh.org/

Thanks
Daniel

**Comment by dmnjohns** [comment]
To address this issue, Repose allows a user to disable certain ciphers. In this case, disabling all DHE ciphers should address the security concern, but it's not necessarily a feasible solution. Still, instructions on how to do so can be found here:

https://repose.atlassian.net/wiki/display/REPOSE/SSL+Termination+Configuration

The other solution is to run Repose in a Java 8 Runtime Environment. This allows the user to pass a Java command line option (or set a system property in a different way) which sets the DH key size to be used. The command line option might look something like:

-Djdk.tls.ephemeralDHKeySize=2048

See the following for more details:
https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html#customizing_dh_keys
