### ISSUE TITLE
daemonize is needed by repose-valve-7.3.0.0-1.noarch

### ISSUE THREAD

**Issue by prem82** [rackerlabs/repose#1428]
Hi All - I get the below error while trying to install repose valve on amazon AWS instance running RHEL.

warning: repose-valve-7.3.0.0-1.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID e7c89bbb: NOKEY
error: Failed dependencies:
        daemonize is needed by repose-valve-7.3.0.0-1.noarch

Could you please let me know what this dependency does and where to get this dependency?

Thanks,
Prem

**Comment by wdschei** [comment]
Prem,

The `daemonize
sudo wget http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
sudo rpm -Uvh rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
sudo yum install -y daemonize

**Comment by wdschei** [comment]
@prem82,

The `daemonize` package is required. We are currently working on the documentation to make this a little more clear. Here are the commands required to install this on RHEL instances that don't already have it installed.
```
sudo wget http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
sudo rpm -Uvh rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
sudo yum install -y daemonize
```

Kindest regards,
Bill
