### ISSUE TITLE
Lots of files in /var/repose

### ISSUE THREAD

**Issue by rphillips** [rackerlabs/repose#1520]
Hi All,

In MaaS our buildbot is seeing a ton of folders/files in /var/repose which will fill up the disk within 2-3 days or so. Any idea why repose would be doing this?

Thanks.

**Comment by Mario-Lopez** [comment]
Hi, Ryan.  Are artifacts being frequently added to Repose or is Repose being frequently restarted?  The /var/repose directory is our "deployment-directory" where we put our extracted artifacts.  You can have Repose clean this up automatically if that's an option for you.  Details on how to configure that are here:  https://repose.atlassian.net/wiki/display/REPOSE/Container

Please let us know if that doesn't work for you.

**Comment by RackerWilliams** [comment]
Hey @rphillips,

You have to tell Repose to clean up after itself, which it should do when it's properly.  Look at your container config you should see something like this

````xml
<deployment-directory auto-clean="true"  />
````

If that is set to true then we have a bug...or you're not shutting down repose correctly...

**Comment by rphillips** [comment]
Awesome. Looks like our chef recipe is setting false. I have a patch, and I'll try it out. Thanks!

**Comment by rphillips** [comment]
Could have been another config issue on that box as well. Thanks! I'll reopen the issue if it persists.
