### ISSUE TITLE
Versioning and default version

### ISSUE THREAD

**Issue by AndreaPivetta** [rackerlabs/repose#1705]
Hi, I'd like to configure the versioning filter to be able to redirect all calls without a specified version to a default version.

`host:port/v1/user` should be equal to `host:port/user` and different to `host:port/v2/user`.

Is there a way to do this?

**Comment by Mario-Lopez** [comment]
Hello.  Are you trying to accomplish this?

```
host:port/user    -> host:port/v1/user
host:port/v1/user -> host:port/v1/user  (no conversion)
host:port/v2/user -> host:port/v2/user  (no conversion)
```

The solution would be similar to this example (where `/api1` would be `/v1` and `/api2` would be `/v2` in your case):
https://repose.atlassian.net/wiki/display/REPOSE/Versioning+filter#Versioningfilter-RoutingbasedonURI

And you would need a couple of adjustments to your System Model.
https://repose.atlassian.net/wiki/display/REPOSE/System+model

You could add a `uri-regex` to your versioning filter in the filter chain (to only have it process the versioned requests), and you could add another endpoint for the non-versioned requests (that would add the `/v1` to the URL).

Your filter chain would include this line:
```
<filter name="versioning" uri-regex="/v[12]/?.*">
```

And your endpoints would look similar to this:
```
<destinations>
    <endpoint id="endpoint0" protocol="http" hostname="some host" root-path="/v1" port="8080" default="true"/>
    <endpoint id="endpoint1" protocol="http" hostname="some host" root-path="" port="8080" default="false"/>
    <endpoint id="endpoint2" protocol="http" hostname="some host" root-path="" port="8080" default="false"/>
</destinations>
```

Does that work for you?

**Comment by ziggy42** [comment]
Works great, thank you!

**Comment by AndreaPivetta** [comment]
Works great, thanks!
