### ISSUE TITLE
Ability to utilize JAVA_HOME in deb/rpm/sysconfig on startup

### ISSUE THREAD

**Issue by dimtruck** [rackerlabs/repose#1706]
As an administrator that runs multiple java versions on an environment, I would like to be able to specify different version than `/usr/bin/java` for repose.

Use case:

```
root@2e076c6d8df5:/opt# service repose-valve start
Repose requires a Java version of at least 8 to function.
Please install a JRE 1.8 or greater.
root@2e076c6d8df5:/opt# java -version
java version "1.7.0_121"
OpenJDK Runtime Environment (IcedTea 2.6.8) (7u121-2.6.8-1ubuntu0.14.04.3)
OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)
root@2e076c6d8df5:/opt# printenv
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
```

Relevate lines:

* https://github.com/rackerlabs/repose/blob/master/repose-aggregator/artifacts/src/config/sysconfig/repose#L3
* https://github.com/rackerlabs/repose/blob/master/repose-aggregator/artifacts/src/config/scripts/repose-valve-deb#L20

Please allow me to overwrite default path of `java` in either of those 2 locations.

**Comment by Mario-Lopez** [comment]
Does this help you?

**Comment by Mario-Lopez** [comment]
Of note, I tested the CentOS instructions to setup the IBM JDK (which has issues for other reasons) a few months ago, and I tested the Ubuntu instructions just now in Vagrant using the latest version of Repose.

**Comment by dimtruck** [comment]
Interesting. 

Right now fighting with

```
# systemctl daemon-reload
bash: systemctl: command not found
```

**Comment by Mario-Lopez** [comment]
Not using systemd?  It's 2017, man.

**Comment by dimtruck** [comment]
we have systemd it seems.  Also, ubuntu 14.04

**Comment by dimtruck** [comment]
Relevant? http://askubuntu.com/a/496385

**Comment by Mario-Lopez** [comment]
For reals?  This is the excuse you need to go to CentOS.

**Comment by dimtruck** [comment]
P.S. this is fine to close if there's a workaround.  My current workaround is sed -e JAVA to point to $JAVA_HOME on sysconfig/repose, which works for me.

**Comment by dimtruck** [comment]
Or.... current Ubuntu :)

**Comment by Mario-Lopez** [comment]
We did a thing for this, but I'm going through it now to understand how it works...

https://github.com/rackerlabs/repose/pull/1404

**Comment by Mario-Lopez** [comment]
Ok, I think what that did was stop hard coding the `java` binary we used from `/usr/bin/java` to what was on the `PATH` which is a step up, I guess.  Can you update your PATH for just the repose-valve service to prefer the correct Java binary?

**Comment by dimtruck** [comment]
so `PATH=$JAVA_HOME/bin/java:$PATH service repose-valve start`?

**Comment by Mario-Lopez** [comment]
I thought it might be something set in `/etc/[sysconfig|default]/repose`.  I haven't DevOp'd in a pre-systemd era environment since 2014. I'll see if Google knows something.

**Comment by Mario-Lopez** [comment]
I didn't see anything that looked promising.  I think it was Damien and Bill that looked into this last time, so I will ping them tomorrow to see if they remember.

**Comment by Mario-Lopez** [comment]
Hi @dimtruck,

Now that I've slept, I can complete the thought I started last night.  Have you tried creating the file:
```
/etc/sysconfig/repose
```

with contents:

```
JAVA=/usr/lib/jvm/java-8-openjdk-amd64/bin/java
```

**Comment by dimtruck** [comment]
@Mario-Lopez That makes sense.  So just stage my own sysconfig.  That seems good.
